global:
  runner: ruby:3.1.2

tasks:
  unit-tests:
    steps:
    - checkout
    - run: bundle install
    - commands:
        - bundle exec rspec

  deploy-to-heroku:
    depends: [unit-tests]
    when: branch == 'production'
    steps:
    - checkout
    - commands:
      - gem install dpl
      - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY

